version: 2.1
default: &default
  working_directory: /app
  docker:
    - image: philophilo/circleci-kube-app
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
      environment:
        DATABASE_USER: $DATABASE_USER
        DATABASE_PASSWORD: $DATABASE_PASSWORD
        DATABASE_NAME: $DATABASE_NAME
        DATABASE_PORT: $DATABASE_PORT
        SECRET_KEY: $SECRET_KEY
        EMAIL_HOST: $EMAIL_HOST
        EMAIL_PORT: $EMAIL_PORT
        EMAIL_HOST_USER: $EMAIL_HOST_USER
        EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
    - image: circleci/postgres:9.6.5-alpine-ram
      environment:
        POSTGRES_USER: $DATABASE_USER
        POSTGRES_DB: $DATABASE_NAME
        POSTGRES_PASSWORD: $DATABASE_PASSWORD

jobs:
  test:
    <<: *default
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            cd api/
            python manage.py test
  deploy:
    <<: *default:
    steps:
      - checkout
      - run:
          command: |
            docker build -f docker/Dockerfile-prod -t philophilo/test .
            docker push philophilo/test
            curl -u $CIRCLECI_TOKEN: -X POST https://circleci.com/api/v2/project/gh/philophilo/fire_k8s/pipeline
